"""Added Cryptos table

Revision ID: 01db33fcb8e8
Revises: 
Create Date: 2022-10-14 16:43:20.189846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01db33fcb8e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptos')
    # ### end Alembic commands ###
